export const GET_WEATHER_START = 'GET_WEATHER_START';
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';
export const GET_WEATHER_FAIL = 'GET_WEATHER_FAIL';

export const GET_DEPARTURES_START = 'GET_DEPARTURES_START';
export const GET_DEPARTURES_SUCCESS = 'GET_DEPARTURES_SUCCESS';
export const GET_DEPARTURES_FAIL = 'GET_DEPARTURES_FAIL';