name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: (cd hallway-dashboard-be && cargo test --verbose)
    - name: Install musl-tools
      run: sudo apt install musl-tools -y
    - name: Add target
      run: rustup target add x86_64-unknown-linux-musl
    - name: Build
      run: |
        cd hallway-dashboard-be
        cargo build --release --target x86_64-unknown-linux-musl
        zip -j lambda.zip ./target/x86_64-unknown-linux-musl/release/bootstrap
