name: Rust

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: (cd hallway-dashboard-be && cargo test --verbose)
    - name: Install musl-tools
      run: sudo apt install musl-tools -y
    - name: Add target
      run: rustup target add x86_64-unknown-linux-musl
    - name: Build
      run: |
        cd hallway-dashboard-be
        cargo build --release --target x86_64-unknown-linux-musl
        zip -j lambda.zip ./target/x86_64-unknown-linux-musl/release/bootstrap
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: lambda-artifact
        path: hallway-dashboard-be/lambda.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: lambda-artifact
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
    - name: Upload lambda to S3
      run: aws s3 cp lambda-artifact/lambda.zip s3://${{ secrets.S3_ARTIFACT_BUCKET }}/hallway-dashboard
    - name: Deploy to AWS
      run: aws cloudformation deploy --template-file template.yml --stack-name hallway-dashboard --capabilities CAPABILITY_IAM --parameter-overrides S3ArtifactBucket=${{ secrets.S3_ARTIFACT_BUCKET }}

