name: Post merge

on:
  push:
    branches: [ master ]
    paths:
    - 'hallway-dashboard-be/**'
    - 'template.yml'

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install musl-tools
      run: sudo apt install musl-tools -y
    - name: Add target
      run: rustup target add x86_64-unknown-linux-musl
    - name: Build
      run: |
        cd hallway-dashboard-be
        cargo build --release --target x86_64-unknown-linux-musl
        zip -j lambda.zip ./target/x86_64-unknown-linux-musl/release/bootstrap
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
    - name: Calculate lambda SHA256
      run: |
        LAMBDA_SHA256=`sha256sum hallway-dashboard-be/lambda.zip | cut -d" " -f1`
        echo "::set-env name=CHECKSUM::$LAMBDA_SHA256"
    - name: Upload lambda to S3
      run: aws s3 cp hallway-dashboard-be/lambda.zip s3://${{ secrets.S3_ARTIFACT_BUCKET }}/hallway-dashboard-$CHECKSUM
    - name: Update S3 key for lambda
      run: sed -i "s/S3-KEY-SET-IN-PIPELINE/hallway-dashboard-$CHECKSUM/" template.yml
    - name: Deploy to AWS
      run: aws cloudformation deploy --template-file template.yml --stack-name hallway-dashboard --capabilities CAPABILITY_IAM --parameter-overrides S3ArtifactBucket=${{ secrets.S3_ARTIFACT_BUCKET }} --no-fail-on-empty-changeset
