name: Post merge

on:
  push:
    branches: [ master ]
    paths:
    - 'hallway-dashboard-be/**'
    - 'template.yml'
    - '.github/**'

jobs:

  build-and-deploy-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Calculate lambda SHA256
      run: |
        LAMBDA_SHA256=`sha256sum /github/home/be/lambda-$GITHUB_SHA.zip | cut -d" " -f1`
        echo "::set-env name=CHECKSUM::$LAMBDA_SHA256"
    - name: Upload lambda to S3
      run: aws s3 cp /github/home/be/lambda-$GITHUB_SHA.zip s3://${{ secrets.S3_ARTIFACT_BUCKET }}/hallway-dashboard-$CHECKSUM
    - name: Update S3 key for lambda
      run: sed -i "s/S3-KEY-SET-IN-PIPELINE/hallway-dashboard-$CHECKSUM/" template.yml
    - name: Deploy to AWS
      run: |
        aws cloudformation deploy --template-file template.yml --stack-name hallway-dashboard --capabilities CAPABILITY_IAM --no-fail-on-empty-changeset --parameter-overrides \
        S3ArtifactBucket=${{ secrets.S3_ARTIFACT_BUCKET }} \
        DarkSkyApiKey=${{ secrets.DARK_SKY_API_KEY }} \
        TrafiklabApiKey=${{ secrets.TRAFIKLAB_API_KEY }} \
        PublicTransportStop=${{ secrets.PUBLIC_TRANSPORT_STOP }} \
        PublicTransportDirection=${{ secrets.PUBLIC_TRANSPORT_DIRECTION }}
  build-and-deploy-frontend:
    needs: build-and-deploy-backend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Obtain stack outputs for build
      run: |
        READ_ACCESS_KEY_ID=`aws cloudformation describe-stacks --stack-name hallway-dashboard --query "Stacks[0].Outputs[?OutputKey=='ReadUserAccessKeyId'].OutputValue" --output text`
        READ_ACCESS_KEY_SECRET=`aws cloudformation describe-stacks --stack-name hallway-dashboard --query "Stacks[0].Outputs[?OutputKey=='ReadUserAccessKeySecret'].OutputValue" --output text`
        STORAGE_BUCKET_NAME=`aws cloudformation describe-stacks --stack-name hallway-dashboard --query "Stacks[0].Outputs[?OutputKey=='StorageBucketName'].OutputValue" --output text`
        echo "::set-env name=READ_ACCESS_KEY_ID::$READ_ACCESS_KEY_ID"
        echo "::set-env name=READ_ACCESS_KEY_SECRET::$READ_ACCESS_KEY_SECRET"
        echo "::set-env name=STORAGE_BUCKET_NAME::$STORAGE_BUCKET_NAME"
    - name: Build frontend
      run: |
        cd hallway-dashboard-fe
        yarn
        REACT_APP_AWS_REGION=${{ secrets.AWS_REGION }} \
        REACT_APP_S3_READ_ACCESS_KEY_ID=$READ_ACCESS_KEY_ID \
        REACT_APP_S3_READ_ACCESS_KEY_SECRET=$READ_ACCESS_KEY_SECRET \
        REACT_APP_STORAGE_BUCKET=$STORAGE_BUCKET_NAME \
        yarn run build
    - name: Obtain stack outputs for deploy
      run: |
        PUBLISH_ACCESS_KEY_ID=`aws cloudformation describe-stacks --stack-name hallway-dashboard --query "Stacks[0].Outputs[?OutputKey=='PublishUserAccessKeyId'].OutputValue" --output text`
        PUBLISH_ACCESS_KEY_SECRET=`aws cloudformation describe-stacks --stack-name hallway-dashboard --query "Stacks[0].Outputs[?OutputKey=='PublishUserAccessKeySecret'].OutputValue" --output text`
        WEB_HOSTING_BUCKET_NAME=`aws cloudformation describe-stacks --stack-name hallway-dashboard --query "Stacks[0].Outputs[?OutputKey=='WebHostingBucketName'].OutputValue" --output text`
        echo "::set-env name=PUBLISH_ACCESS_KEY_ID::$PUBLISH_ACCESS_KEY_ID"
        echo "::set-env name=PUBLISH_ACCESS_KEY_SECRET::$PUBLISH_ACCESS_KEY_SECRET"
        echo "::set-env name=WEB_HOSTING_BUCKET_NAME::$WEB_HOSTING_BUCKET_NAME"
    - name: Deploy frontend
      run: |
        AWS_ACCESS_KEY_ID=$PUBLISH_ACCESS_KEY_ID \
        AWS_SECRET_ACCESS_KEY=$PUBLISH_ACCESS_KEY_SECRET \
        aws s3 sync hallway-dashboard-fe/build s3://$WEB_HOSTING_BUCKET_NAME
