name: Pre merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: CloudFormation Lint
      uses: scottbrenner/cfn-lint-action@master
      with:
        args: template.yml

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Unit tests
      run: (cd hallway-dashboard-be && cargo test --verbose)
