name: Pre merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  cfn-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: cfn-lint
      uses: scottbrenner/cfn-lint-action@master
      with:
        args: template.yml

  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Unit tests
      run: (cd hallway-dashboard-be && cargo test --verbose)
