name: Pre merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: CloudFormation Lint
      uses: scottbrenner/cfn-lint-action@master
      with:
        args: template.yml

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Unit tests
      run: (cd hallway-dashboard-be && cargo test -- --test-threads=1)

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install required tools
      run: sudo apt install musl-tools -y
    - name: Add target
      run: rustup target add x86_64-unknown-linux-musl
    - name: Build
      run: |
        cd hallway-dashboard-be
        PKG_CONFIG_ALLOW_CROSS=1 cargo build --release --target x86_64-unknown-linux-musl
